import axios from "axios";

const BACKEDN_URL = "https://rncourse5-default-rtdb.firebaseio.com";

export async function storeExpense(expenseData) {
  const response = await axios.post(BACKEDN_URL + "/expenses.json", expenseData);
  //name is de ID generated by Firebase
  const id = response.data.name; 
  return id;
}

export async function fetchExpenses() {
  const response = await axios.get(BACKEDN_URL + "/expenses.json");

  const expenses = [];
  for (const key in response.data) {
    const expenseObj = {
      id: key,
      amount: response.data[key].amount,
      date: new Date(response.data[key].date),
      description: response.data[key].description,
    };
    expenses.push(expenseObj);
  }
  return expenses;
}

export function updatedExpense(id, expenseData){
    return axios.put(BACKEDN_URL + `/expenses/${id}.json`, expenseData);
}

export async function deleteExpense(id){
    return axios.delete(BACKEDN_URL + `/expenses/${id}.json`);
}